<?php

/**
 * @file
 * Install, update and uninstall functions for the legacy_reference module.
 */

/**
 * Implements hook_field_schema().
 */
function legacy_reference_field_schema($field) {
  if ($field['type'] == 'legacy_reference') {
    return array(
      'columns' => array(
        'value' => array(
          'type' => 'text',
          'size' => 'big',
          'not null' => FALSE,
        ),
      ),
    );
  }
}
